version: '3.7'

services:
    membership-front:
        container_name: membership-front
        image: membership-front:dev
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - 3000:3000
